import 'package:flutter/material.dart';
import 'package:mobile_scanner/mobile_scanner.dart';

/// Full-screen QR code scanner.
/// Pops with the scanned URL string, or null if the user cancels.
///
/// Usage:
/// ```dart
/// final url = await Navigator.push<String>(
///   context,
///   MaterialPageRoute(builder: (_) => const QrScannerPage()),
/// );
/// if (url != null) { /* use url */ }
/// ```
class QrScannerPage extends StatefulWidget {
  const QrScannerPage({super.key});

  @override
  State<QrScannerPage> createState() => _QrScannerPageState();
}

class _QrScannerPageState extends State<QrScannerPage> {
  final MobileScannerController _controller = MobileScannerController(
    detectionSpeed: DetectionSpeed.noDuplicates,
    returnImage: false,
  );

  bool _scanned = false;
  bool _torchOn  = false;

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  void _onDetect(BarcodeCapture capture) {
    if (_scanned) return;
    final raw = capture.barcodes.firstOrNull?.rawValue;
    if (raw == null || raw.isEmpty) return;

    // Accept anything that looks like a URL
    final trimmed = raw.trim();
    if (!trimmed.startsWith('http://') && !trimmed.startsWith('https://')) {
      _showInvalid(trimmed);
      return;
    }

    _scanned = true;
    Navigator.of(context).pop(trimmed);
  }

  void _showInvalid(String value) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text('Not a valid URL: $value'),
        backgroundColor: Colors.red.shade700,
        behavior: SnackBarBehavior.floating,
        duration: const Duration(seconds: 2),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.black,
      appBar: AppBar(
        backgroundColor: Colors.black,
        foregroundColor: Colors.white,
        title: const Text('Scan Server QR Code'),
        actions: [
          IconButton(
            icon: Icon(_torchOn ? Icons.flash_on : Icons.flash_off),
            tooltip: 'Toggle torch',
            onPressed: () {
              _controller.toggleTorch();
              setState(() => _torchOn = !_torchOn);
            },
          ),
          IconButton(
            icon: const Icon(Icons.flip_camera_ios_outlined),
            tooltip: 'Flip camera',
            onPressed: _controller.switchCamera,
          ),
        ],
      ),
      body: Stack(
        children: [
          // Camera feed
          MobileScanner(
            controller: _controller,
            onDetect: _onDetect,
          ),

          // Scan frame overlay
          Center(
            child: Container(
              width: 260,
              height: 260,
              decoration: BoxDecoration(
                border: Border.all(color: Colors.white, width: 2),
                borderRadius: BorderRadius.circular(16),
              ),
              child: ClipRRect(
                borderRadius: BorderRadius.circular(14),
                child: Stack(
                  children: [
                    // Corner accents
                    _Corner(top: true,  left: true),
                    _Corner(top: true,  left: false),
                    _Corner(top: false, left: true),
                    _Corner(top: false, left: false),
                  ],
                ),
              ),
            ),
          ),

          // Instruction text
          Positioned(
            bottom: 60,
            left: 0,
            right: 0,
            child: Column(
              children: [
                const Icon(Icons.qr_code_2, color: Colors.white54, size: 32),
                const SizedBox(height: 10),
                const Text(
                  'Point the camera at the server QR code',
                  textAlign: TextAlign.center,
                  style: TextStyle(color: Colors.white70, fontSize: 14),
                ),
                const SizedBox(height: 4),
                Text(
                  'Generated by: cloudflared tunnel --url http://localhost:3000',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.white38,
                    fontSize: 11,
                    fontFamily: 'monospace',
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

/// Coloured corner accent inside the scan frame.
class _Corner extends StatelessWidget {
  final bool top;
  final bool left;
  const _Corner({required this.top, required this.left});

  @override
  Widget build(BuildContext context) {
    return Positioned(
      top:    top  ? 0 : null,
      bottom: top  ? null : 0,
      left:   left ? 0 : null,
      right:  left ? null : 0,
      child: Container(
        width: 28,
        height: 28,
        decoration: BoxDecoration(
          border: Border(
            top:    top  ? const BorderSide(color: Colors.greenAccent, width: 3) : BorderSide.none,
            bottom: top  ? BorderSide.none : const BorderSide(color: Colors.greenAccent, width: 3),
            left:   left ? const BorderSide(color: Colors.greenAccent, width: 3) : BorderSide.none,
            right:  left ? BorderSide.none : const BorderSide(color: Colors.greenAccent, width: 3),
          ),
        ),
      ),
    );
  }
}
