services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-dev

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-dev
