services:
  db:
    image: postgres:15-alpine
    container_name: setu_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: setu_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: setu_app
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: admin
      DATABASE_PASSWORD: password
      DATABASE_NAME: setu_db
      JWT_SECRET: supersecretkey
      PDF_TOOL_URL: http://pdf-tool:8002
      FIREBASE_SERVICE_ACCOUNT_PATH: firebase-service-account.json
      RUN_DB_MIGRATIONS: "true"
      DB_MIGRATION_SCRIPT: migration:run:dist
    volumes:
      - ./backend/uploads:/usr/src/app/uploads

  pdf-tool:
    build:
      context: ./tools/pdf_processor
      dockerfile: Dockerfile
    container_name: setu_pdf_tool
    ports:
      - "8001:8001"
    restart: always

volumes:
  postgres_data:
