/**
 * Provider-agnostic interface for AI text generation.
 *
 * Every concrete provider (OpenRouter, Azure OpenAI, plain OpenAI) must
 * implement this interface.  The InsightAiService uses this interface so
 * swapping providers is a zero-code-change operation.
 */
export interface AiCompletionRequest {
  /** System-level instruction (role context). */
  systemPrompt?: string;
  /** Main user prompt. */
  userPrompt: string;
  /** Override the config-level model name if needed. */
  modelOverride?: string;
  maxTokens?: number;
  temperature?: number;
}

export interface AiCompletionResponse {
  /** The full text generated by the model. */
  text: string;
  /** Actual model identifier returned by the provider. */
  modelUsed: string;
  /** Total tokens consumed (prompt + completion). */
  tokensUsed: number | null;
  /** Provider finish reason such as stop / length when available. */
  finishReason?: string | null;
  /** Raw provider response object for debugging. */
  raw: unknown;
}

export interface IAiProvider {
  /**
   * Send a completion request to the underlying AI provider.
   * Throws on network/auth/quota errors — callers should catch and handle.
   */
  complete(request: AiCompletionRequest): Promise<AiCompletionResponse>;
}
