/**
 * Permission Config — Re-exports from the central Permission Registry.
 *
 * This file exists for backward compatibility. All permission definitions,
 * dependencies, and the expansion function now live in permission-registry.ts.
 *
 * ⚠️ DO NOT add permissions here. Add them to permission-registry.ts instead.
 */

export {
  PERMISSION_DEPENDENCIES,
  expandPermissions,
  ALL_PERMISSIONS,
} from './permission-registry';

/**
 * PermissionCode constants — kept for backward compatibility with backend code
 * that imports `PermissionCode.XXX` from this file.
 *
 * These codes MUST match the registry codes exactly.
 */
export const PermissionCode = {
  // ─── System-Level (Legacy) ────────────────────────────────────────────────
  VIEW_DASHBOARD: 'VIEW_DASHBOARD',
  VIEW_PROJECTS: 'VIEW_PROJECTS',
  MANAGE_USERS: 'MANAGE_USERS',
  MANAGE_ROLES: 'MANAGE_ROLES',
  MANAGE_EPS: 'MANAGE_EPS',

  // ─── EPS ──────────────────────────────────────────────────────────────────
  EPS_NODE_READ: 'EPS.NODE.READ',
  EPS_NODE_CREATE: 'EPS.NODE.CREATE',
  EPS_NODE_UPDATE: 'EPS.NODE.UPDATE',
  EPS_NODE_DELETE: 'EPS.NODE.DELETE',
  EPS_NODE_IMPORT: 'EPS.NODE.IMPORT',

  // ─── Project ──────────────────────────────────────────────────────────────
  PROJECT_PROPS_READ: 'PROJECT.PROPERTIES.READ',
  PROJECT_PROPS_UPDATE: 'PROJECT.PROPERTIES.UPDATE',
  PROJECT_TEAM_READ: 'PROJECT.TEAM.READ',
  PROJECT_TEAM_MANAGE: 'PROJECT.TEAM.MANAGE',

  // ─── WBS ──────────────────────────────────────────────────────────────────
  WBS_NODE_READ: 'WBS.NODE.READ',
  WBS_NODE_CREATE: 'WBS.NODE.CREATE',
  WBS_NODE_UPDATE: 'WBS.NODE.UPDATE',
  WBS_NODE_DELETE: 'WBS.NODE.DELETE',
  WBS_NODE_IMPORT: 'WBS.NODE.IMPORT',
  WBS_ACTIVITY_READ: 'WBS.ACTIVITY.READ',
  WBS_ACTIVITY_CREATE: 'WBS.ACTIVITY.CREATE',
  WBS_ACTIVITY_UPDATE: 'WBS.ACTIVITY.UPDATE',
  WBS_ACTIVITY_DELETE: 'WBS.ACTIVITY.DELETE',
  WBS_TEMPLATE_READ: 'WBS.TEMPLATE.READ',
  WBS_TEMPLATE_APPLY: 'WBS.TEMPLATE.APPLY',
  WBS_TEMPLATE_MANAGE: 'WBS.TEMPLATE.MANAGE',

  // ─── Schedule ─────────────────────────────────────────────────────────────
  SCHEDULE_READ: 'SCHEDULE.READ',
  SCHEDULE_UPDATE: 'SCHEDULE.UPDATE',
  SCHEDULE_IMPORT: 'SCHEDULE.IMPORT',
  SCHEDULE_VERSION_CREATE: 'SCHEDULE.VERSION.CREATE',
  SCHEDULE_VERSION_READ: 'SCHEDULE.VERSION.READ',
  SCHEDULE_CALENDAR_READ: 'SCHEDULE.CALENDAR.READ',
  SCHEDULE_CALENDAR_CREATE: 'SCHEDULE.CALENDAR.CREATE',
  SCHEDULE_CALENDAR_UPDATE: 'SCHEDULE.CALENDAR.UPDATE',
  SCHEDULE_CALENDAR_DELETE: 'SCHEDULE.CALENDAR.DELETE',

  // ─── BOQ ──────────────────────────────────────────────────────────────────
  BOQ_ITEM_READ: 'BOQ.ITEM.READ',
  BOQ_ITEM_CREATE: 'BOQ.ITEM.CREATE',
  BOQ_ITEM_UPDATE: 'BOQ.ITEM.UPDATE',
  BOQ_ITEM_DELETE: 'BOQ.ITEM.DELETE',
  BOQ_ITEM_IMPORT: 'BOQ.ITEM.IMPORT',
  BOQ_MEASUREMENT_MANAGE: 'BOQ.MEASUREMENT.MANAGE',
  BOQ_MEASUREMENT_IMPORT: 'BOQ.MEASUREMENT.IMPORT',
  BOQ_PROGRESS_CREATE: 'BOQ.PROGRESS.CREATE',

  // ─── Planning ─────────────────────────────────────────────────────────────
  PLANNING_MATRIX_READ: 'PLANNING.MATRIX.READ',
  PLANNING_MATRIX_UPDATE: 'PLANNING.MATRIX.UPDATE',
  PLANNING_ANALYSIS_READ: 'PLANNING.ANALYSIS.READ',
  PLANNING_RECOVERY_MANAGE: 'PLANNING.RECOVERY.MANAGE',
  PLANNING_LOOKAHEAD_CREATE: 'PLANNING.LOOKAHEAD.CREATE',
  RELEASE_STRATEGY_READ: 'RELEASE_STRATEGY.READ',
  RELEASE_STRATEGY_WRITE: 'RELEASE_STRATEGY.WRITE',
  RELEASE_STRATEGY_ACTIVATE: 'RELEASE_STRATEGY.ACTIVATE',
  RELEASE_STRATEGY_SIMULATE: 'RELEASE_STRATEGY.SIMULATE',

  // ─── Execution ────────────────────────────────────────────────────────────
  EXECUTION_ENTRY_READ: 'EXECUTION.ENTRY.READ',
  EXECUTION_ENTRY_CREATE: 'EXECUTION.ENTRY.CREATE',
  EXECUTION_ENTRY_UPDATE: 'EXECUTION.ENTRY.UPDATE',
  EXECUTION_ENTRY_DELETE: 'EXECUTION.ENTRY.DELETE',
  EXECUTION_MICRO_CREATE: 'EXECUTION.MICRO.CREATE',
  EXECUTION_ENTRY_APPROVE: 'EXECUTION.ENTRY.APPROVE',

  // ─── Micro Schedule ───────────────────────────────────────────────────────
  MICRO_SCHEDULE_READ: 'MICRO.SCHEDULE.READ',
  MICRO_SCHEDULE_CREATE: 'MICRO.SCHEDULE.CREATE',
  MICRO_SCHEDULE_UPDATE: 'MICRO.SCHEDULE.UPDATE',
  MICRO_SCHEDULE_DELETE: 'MICRO.SCHEDULE.DELETE',
  MICRO_SCHEDULE_SUBMIT: 'MICRO.SCHEDULE.SUBMIT',
  MICRO_SCHEDULE_APPROVE: 'MICRO.SCHEDULE.APPROVE',
  MICRO_SCHEDULE_MANAGE: 'MICRO.SCHEDULE.MANAGE',
  MICRO_ACTIVITY_READ: 'MICRO.ACTIVITY.READ',
  MICRO_ACTIVITY_CREATE: 'MICRO.ACTIVITY.CREATE',
  MICRO_ACTIVITY_UPDATE: 'MICRO.ACTIVITY.UPDATE',
  MICRO_ACTIVITY_DELETE: 'MICRO.ACTIVITY.DELETE',
  MICRO_LOG_CREATE: 'MICRO.LOG.CREATE',
  MICRO_LOG_UPDATE: 'MICRO.LOG.UPDATE',
  MICRO_LOG_DELETE: 'MICRO.LOG.DELETE',

  // ─── Progress ─────────────────────────────────────────────────────────────
  PROGRESS_DASHBOARD_READ: 'PROGRESS.DASHBOARD.READ',
  PROGRESS_INSIGHTS_READ: 'PROGRESS.INSIGHTS.READ',

  // ─── Labor ────────────────────────────────────────────────────────────────
  LABOR_CATEGORY_READ: 'LABOR.CATEGORY.READ',
  LABOR_CATEGORY_MANAGE: 'LABOR.CATEGORY.MANAGE',
  LABOR_ENTRY_READ: 'LABOR.ENTRY.READ',
  LABOR_ENTRY_CREATE: 'LABOR.ENTRY.CREATE',
  LABOR_MAPPING_MANAGE: 'LABOR.MAPPING.MANAGE',
  LABOR_ENTRY_IMPORT: 'LABOR.ENTRY.IMPORT',

  // ─── EHS ──────────────────────────────────────────────────────────────────
  EHS_DASHBOARD_READ: 'EHS.DASHBOARD.READ',
  EHS_OBSERVATION_READ: 'EHS.OBSERVATION.READ',
  EHS_OBSERVATION_CREATE: 'EHS.OBSERVATION.CREATE',
  EHS_OBSERVATION_UPDATE: 'EHS.OBSERVATION.UPDATE',
  EHS_OBSERVATION_DELETE: 'EHS.OBSERVATION.DELETE',
  EHS_INCIDENT_READ: 'EHS.INCIDENT.READ',
  EHS_INCIDENT_CREATE: 'EHS.INCIDENT.CREATE',
  EHS_INCIDENT_UPDATE: 'EHS.INCIDENT.UPDATE',
  EHS_INCIDENT_DELETE: 'EHS.INCIDENT.DELETE',
  EHS_INSPECTION_READ: 'EHS.INSPECTION.READ',
  EHS_INSPECTION_CREATE: 'EHS.INSPECTION.CREATE',
  EHS_INSPECTION_UPDATE: 'EHS.INSPECTION.UPDATE',
  EHS_INSPECTION_DELETE: 'EHS.INSPECTION.DELETE',
  EHS_TRAINING_READ: 'EHS.TRAINING.READ',
  EHS_TRAINING_CREATE: 'EHS.TRAINING.CREATE',
  EHS_TRAINING_UPDATE: 'EHS.TRAINING.UPDATE',
  EHS_TRAINING_DELETE: 'EHS.TRAINING.DELETE',
  EHS_ENVIRONMENTAL_READ: 'EHS.ENVIRONMENTAL.READ',
  EHS_ENVIRONMENTAL_CREATE: 'EHS.ENVIRONMENTAL.CREATE',
  EHS_LEGAL_READ: 'EHS.LEGAL.READ',
  EHS_LEGAL_MANAGE: 'EHS.LEGAL.MANAGE',
  EHS_MACHINERY_MANAGE: 'EHS.MACHINERY.MANAGE',
  EHS_PERFORMANCE_MANAGE: 'EHS.PERFORMANCE.MANAGE',
  EHS_COMPETENCY_MANAGE: 'EHS.COMPETENCY.MANAGE',
  EHS_VEHICLE_MANAGE: 'EHS.VEHICLE.MANAGE',
  EHS_INCIDENTREGISTER_MANAGE: 'EHS.INCIDENTREGISTER.MANAGE',
  EHS_MANHOUR_READ: 'EHS.MANHOUR.READ',
  EHS_MANHOUR_CREATE: 'EHS.MANHOUR.CREATE',

  // ─── Quality ──────────────────────────────────────────────────────────────
  QUALITY_DASHBOARD_READ: 'QUALITY.DASHBOARD.READ',
  QUALITY_CHECKLIST_READ: 'QUALITY.CHECKLIST.READ',
  QUALITY_CHECKLIST_CREATE: 'QUALITY.CHECKLIST.CREATE',
  QUALITY_CHECKLIST_UPDATE: 'QUALITY.CHECKLIST.UPDATE',
  QUALITY_CHECKLIST_DELETE: 'QUALITY.CHECKLIST.DELETE',
  QUALITY_TEST_READ: 'QUALITY.TEST.READ',
  QUALITY_TEST_CREATE: 'QUALITY.TEST.CREATE',
  QUALITY_TEST_UPDATE: 'QUALITY.TEST.UPDATE',
  QUALITY_TEST_DELETE: 'QUALITY.TEST.DELETE',
  QUALITY_TEST_MANAGE: 'QUALITY.TEST.MANAGE',
  QUALITY_NCR_READ: 'QUALITY.NCR.READ',
  QUALITY_NCR_CREATE: 'QUALITY.NCR.CREATE',
  QUALITY_NCR_UPDATE: 'QUALITY.NCR.UPDATE',
  QUALITY_NCR_DELETE: 'QUALITY.NCR.DELETE',
  QUALITY_SNAG_READ: 'QUALITY.SNAG.READ',
  QUALITY_SNAG_CREATE: 'QUALITY.SNAG.CREATE',
  QUALITY_SNAG_UPDATE: 'QUALITY.SNAG.UPDATE',
  QUALITY_SNAG_DELETE: 'QUALITY.SNAG.DELETE',
  QUALITY_AUDIT_READ: 'QUALITY.AUDIT.READ',
  QUALITY_AUDIT_CREATE: 'QUALITY.AUDIT.CREATE',
  QUALITY_AUDIT_UPDATE: 'QUALITY.AUDIT.UPDATE',
  QUALITY_AUDIT_DELETE: 'QUALITY.AUDIT.DELETE',
  QUALITY_DOCUMENT_READ: 'QUALITY.DOCUMENT.READ',
  QUALITY_DOCUMENT_MANAGE: 'QUALITY.DOCUMENT.MANAGE',
  QUALITY_ACTIVITYLIST_READ: 'QUALITY.ACTIVITYLIST.READ',
  QUALITY_ACTIVITYLIST_CREATE: 'QUALITY.ACTIVITYLIST.CREATE',
  QUALITY_ACTIVITYLIST_UPDATE: 'QUALITY.ACTIVITYLIST.UPDATE',
  QUALITY_ACTIVITYLIST_DELETE: 'QUALITY.ACTIVITYLIST.DELETE',
  QUALITY_ACTIVITYLIST_MANAGE: 'QUALITY.ACTIVITYLIST.MANAGE',
  QUALITY_ACTIVITY_READ: 'QUALITY.ACTIVITY.READ',
  QUALITY_ACTIVITY_CREATE: 'QUALITY.ACTIVITY.CREATE',
  QUALITY_ACTIVITY_UPDATE: 'QUALITY.ACTIVITY.UPDATE',
  QUALITY_ACTIVITY_DELETE: 'QUALITY.ACTIVITY.DELETE',
  QUALITY_SEQUENCE_READ: 'QUALITY.SEQUENCE.READ',
  QUALITY_SEQUENCE_UPDATE: 'QUALITY.SEQUENCE.UPDATE',
  QUALITY_INSPECTION_READ: 'QUALITY.INSPECTION.READ',
  QUALITY_INSPECTION_RAISE: 'QUALITY.INSPECTION.RAISE',
  QUALITY_INSPECTION_APPROVE: 'QUALITY.INSPECTION.APPROVE',
  QUALITY_ACTIVITY_APPROVE: 'QUALITY.ACTIVITY.APPROVE',
  QUALITY_OBSERVATION_CREATE: 'QUALITY.OBSERVATION.CREATE',
  QUALITY_OBSERVATION_RESOLVE: 'QUALITY.OBSERVATION.RESOLVE',
  QUALITY_STRUCTURE_MANAGE: 'QUALITY.STRUCTURE.MANAGE',

  // ─── Design ───────────────────────────────────────────────────────────────
  DESIGN_CATEGORY_READ: 'DESIGN.CATEGORY.READ',
  DESIGN_CATEGORY_CREATE: 'DESIGN.CATEGORY.CREATE',
  DESIGN_DRAWING_READ: 'DESIGN.DRAWING.READ',
  DESIGN_DRAWING_CREATE: 'DESIGN.DRAWING.CREATE',
  DESIGN_DRAWING_UPLOAD: 'DESIGN.DRAWING.UPLOAD',
  DESIGN_DRAWING_UPDATE: 'DESIGN.DRAWING.UPDATE',
  DESIGN_DRAWING_DELETE: 'DESIGN.DRAWING.DELETE',
  DESIGN_DRAWING_APPROVE: 'DESIGN.DRAWING.APPROVE',

  // ─── Work Orders ──────────────────────────────────────────────────────────
  WORKORDER_VENDOR_READ: 'WORKORDER.VENDOR.READ',
  WORKORDER_VENDOR_CREATE: 'WORKORDER.VENDOR.CREATE',
  WORKORDER_VENDOR_UPDATE: 'WORKORDER.VENDOR.UPDATE',
  WORKORDER_VENDOR_DELETE: 'WORKORDER.VENDOR.DELETE',
  WORKORDER_ORDER_READ: 'WORKORDER.ORDER.READ',
  WORKORDER_ORDER_CREATE: 'WORKORDER.ORDER.CREATE',
  WORKORDER_ORDER_IMPORT: 'WORKORDER.ORDER.IMPORT',
  WORKORDER_ORDER_DELETE: 'WORKORDER.ORDER.DELETE',
  WORKORDER_MAPPING_READ: 'WORKORDER.MAPPING.READ',
  WORKORDER_MAPPING_MANAGE: 'WORKORDER.MAPPING.MANAGE',
  WORKORDER_TEMPLATE_MANAGE: 'WORKORDER.TEMPLATE.MANAGE',

  // ─── Resources ────────────────────────────────────────────────────────────
  RESOURCE_MASTER_READ: 'RESOURCE.MASTER.READ',
  RESOURCE_MASTER_CREATE: 'RESOURCE.MASTER.CREATE',
  RESOURCE_MASTER_UPDATE: 'RESOURCE.MASTER.UPDATE',
  RESOURCE_MASTER_DELETE: 'RESOURCE.MASTER.DELETE',
  RESOURCE_MASTER_IMPORT: 'RESOURCE.MASTER.IMPORT',
  RESOURCE_TEMPLATE_MANAGE: 'RESOURCE.TEMPLATE.MANAGE',

  // ─── Dashboard ────────────────────────────────────────────────────────────
  DASHBOARD_SUMMARY_READ: 'DASHBOARD.SUMMARY.READ',
  DASHBOARD_ANALYTICS_READ: 'DASHBOARD.ANALYTICS.READ',
  DASHBOARD_ALERTS_READ: 'DASHBOARD.ALERTS.READ',

  // ─── Admin ────────────────────────────────────────────────────────────────
  USER_MANAGEMENT_READ: 'USER.MANAGEMENT.READ',
  USER_MANAGEMENT_CREATE: 'USER.MANAGEMENT.CREATE',
  USER_MANAGEMENT_UPDATE: 'USER.MANAGEMENT.UPDATE',
  USER_MANAGEMENT_DELETE: 'USER.MANAGEMENT.DELETE',
  ROLE_MANAGEMENT_READ: 'ROLE.MANAGEMENT.READ',
  ROLE_MANAGEMENT_CREATE: 'ROLE.MANAGEMENT.CREATE',
  ROLE_MANAGEMENT_UPDATE: 'ROLE.MANAGEMENT.UPDATE',
  ROLE_MANAGEMENT_DELETE: 'ROLE.MANAGEMENT.DELETE',
  AUDIT_LOG_READ: 'AUDIT.LOG.READ',
  AUDIT_READ: 'AUDIT.READ',
  ADMIN_SETTINGS_MANAGE: 'ADMIN.SETTINGS.MANAGE',
  ADMIN_TEMPLATE_MANAGE: 'ADMIN.TEMPLATE.MANAGE',

  // ─── Template Builder ─────────────────────────────────────────────────────
  TEMPLATE_BUILDER_READ: 'TEMPLATE.BUILDER.READ',
  TEMPLATE_BUILDER_CREATE: 'TEMPLATE.BUILDER.CREATE',
  TEMPLATE_BUILDER_UPDATE: 'TEMPLATE.BUILDER.UPDATE',
  TEMPLATE_BUILDER_DELETE: 'TEMPLATE.BUILDER.DELETE',
  TEMPLATE_BUILDER_IMPORT: 'TEMPLATE.BUILDER.IMPORT',

  // ─── Dashboard Builder ────────────────────────────────────────────────────
  ADMIN_DASHBOARD_READ: 'ADMIN.DASHBOARD.READ',
  ADMIN_DASHBOARD_CREATE: 'ADMIN.DASHBOARD.CREATE',
  ADMIN_DASHBOARD_UPDATE: 'ADMIN.DASHBOARD.UPDATE',
  ADMIN_DASHBOARD_DELETE: 'ADMIN.DASHBOARD.DELETE',
  ADMIN_REPORT_READ: 'ADMIN.REPORT.READ',
  ADMIN_REPORT_CREATE: 'ADMIN.REPORT.CREATE',
  ADMIN_REPORT_UPDATE: 'ADMIN.REPORT.UPDATE',
  ADMIN_REPORT_DELETE: 'ADMIN.REPORT.DELETE',
  ADMIN_REPORT_MANAGE: 'ADMIN.REPORT.MANAGE',
} as const;

export type Permission = (typeof PermissionCode)[keyof typeof PermissionCode];
